# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: alastria.com
    Specs:
      - Hostname: orderer
      
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Caixabank
    Domain: caixabank.alastria.com
    Template:
      Count: 1
    Users:
      Count: 1


  - Name: Alastria
    Domain: alastria.alastria.com
    Template:
      Count: 1
    Users:
      Count: 1
